[user]
name = "marin"
email = "git+jj@mar.in"

[ui]
default-command = "log"

[template-aliases]
'format_short_id(id)' = 'id.shortest()'
'format_timestamp(timestamp)' = 'timestamp.ago()'

[aliases]
b = [ "bookmark" ]
d = [ "diff" ]
e = [ "edit" ]
